name: Generate Trophy
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  trophy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: YeshuaChavez
          token: ${{ secrets.PAT_TOKEN }}
          file: trophy.svg
          theme: nord

      - name: Commit trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add trophy.svg
          git diff --staged --quiet || (git commit -m "Update trophy" && git push)
